import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0d0015',
  },
  backgroundImage: {
    opacity: 0.3,
  },
  backgroundOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 3, 33, 0.7)',
  },
  birthdayContainer: {
    flex: 1,
    padding: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  birthdayTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#e9d5ff',
    marginTop: 24,
    marginBottom: 12,
    textAlign: 'center',
  },
  birthdaySubtitle: {
    fontSize: 16,
    color: '#c4b5fd',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 24,
  },
  birthdayInputs: {
    flexDirection: 'row',
    gap: 30,
    marginBottom: 32,
    justifyContent: 'center',
  },
  inputGroup: {
    alignItems: 'center',
    minWidth: 120,
  },
  inputLabel: {
    fontSize: 16,
    color: '#c4b5fd',
    marginBottom: 10,
    textAlign: 'center',
    fontWeight: '500',
  },
  birthdayInput: {
    width: 100,
    height: 60,
    backgroundColor: '#2d1b4e',
    borderRadius: 12,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#e9d5ff',
    textAlign: 'center',
    borderWidth: 2,
    borderColor: '#7c3aed',
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7c3aed',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 25,
    gap: 12,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  skipButton: {
    marginTop: 16,
    padding: 12,
  },
  skipButtonText: {
    color: '#9f7aea',
    fontSize: 16,
  },
  selectionContainer: {
    padding: 12,
    paddingTop: 0,
  },
  heroSection: {
    height: 170,
    position: 'relative',
    marginHorizontal: -12,
    overflow: 'hidden',
  },
  heroImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 14,
    alignItems: 'center',
  },
  heroEyebrow: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: '#fbbf24',
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    marginBottom: 4,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
    textShadowColor: 'rgba(168,85,247,0.7)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  heroGlyphRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6, marginBottom: 4 },
  heroGlyphLine: { width: 32, height: 1, backgroundColor: 'rgba(251,191,36,0.6)' },
  heroSubtitle: {
    fontSize: 12,
    color: '#c4b5fd',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
    marginTop: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#e9d5ff',
    marginTop: 16,
  },
  subtitle: {
    fontSize: 16,
    color: '#c4b5fd',
    marginTop: 8,
  },
  enterBirthdayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    backgroundColor: 'rgba(124, 58, 237, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 8,
    borderWidth: 1,
    borderColor: '#7c3aed',
  },
  enterBirthdayText: {
    color: '#b794f6',
    fontSize: 14,
    fontWeight: '500',
  },
  suggestedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a0033',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: '#f59e0b',
    gap: 12,
  },
  suggestedText: {
    flex: 1,
    fontSize: 14,
    color: '#e9d5ff',
    lineHeight: 20,
  },
  guidesGrid: {
    gap: 16,
  },
  guideCard: {
    backgroundColor: '#1a0033',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2d1b4e',
    width: '100%',
  },
  guideCardSuggested: {
    borderColor: '#f59e0b',
    borderWidth: 2,
  },
  guideIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  guideImageContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    overflow: 'hidden',
    marginBottom: 16,
    borderWidth: 3,
    borderColor: '#7c3aed',
  },
  guideImage: {
    width: '100%',
    height: '100%',
  },
  guideName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#e9d5ff',
    marginBottom: 4,
  },
  guideElement: {
    fontSize: 16,
    color: '#b794f6',
    marginBottom: 8,
    fontWeight: '500',
  },
  guideGender: {
    fontSize: 14,
    color: '#c4b5fd',
    marginBottom: 12,
  },
  guideDescription: {
    fontSize: 14,
    color: '#c4b5fd',
    textAlign: 'center',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#1a0033',
    borderBottomWidth: 1,
    borderBottomColor: '#2d1b4e',
  },
  backButton: {
    marginRight: 12,
  },
  chatHeaderInfo: {
    flex: 1,
  },
  chatHeaderName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#e9d5ff',
  },
  chatHeaderElement: {
    fontSize: 14,
    color: '#c4b5fd',
  },
  chatHeaderIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatHeaderImageWrapper: {
    position: 'relative',
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  pulseRing: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    backgroundColor: 'transparent',
  },
  chatHeaderImageContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#7c3aed',
  },
  chatHeaderImage: {
    width: '100%',
    height: '100%',
  },
  changeBirthdayLink: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 4,
  },
  changeBirthdayText: {
    color: '#9f7aea',
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  saveJournalButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  messagesContainer: {
    flex: 1,
  },
  messagesContent: {
    padding: 16,
  },
  messageBubble: {
    maxWidth: '80%',
    padding: 12,
    borderRadius: 16,
    marginBottom: 12,
  },
  userMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#7c3aed',
  },
  assistantMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#2d1b4e',
  },
  messageText: {
    fontSize: 16,
    lineHeight: 22,
  },
  userMessageText: {
    color: '#fff',
  },
  assistantMessageText: {
    color: '#e9d5ff',
  },
  audioButton: {
    marginTop: 8,
    padding: 4,
  },
  inputContainer: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: '#1a0033',
    borderTopWidth: 1,
    borderTopColor: '#2d1b4e',
    alignItems: 'flex-end',
  },
  input: {
    flex: 1,
    backgroundColor: '#2d1b4e',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: '#e9d5ff',
    fontSize: 16,
    maxHeight: 100,
    marginRight: 12,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockedContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  lockedIcon: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 215, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  lockedTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#e9d5ff',
    marginBottom: 8,
  },
  lockedSubtitle: {
    fontSize: 16,
    color: '#ffd700',
    fontWeight: '600',
    marginBottom: 16,
  },
  lockedDescription: {
    fontSize: 16,
    color: '#c4b5fd',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
  },
  unlockButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#b794f6',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 25,
    gap: 8,
  },
  unlockButtonText: {
    color: '#1a0033',
    fontSize: 18,
    fontWeight: 'bold',
  },
  priceText: {
    marginTop: 16,
    fontSize: 14,
    color: '#9f7aea',
  },
  chatHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  muteButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2d1b4e',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#7c3aed',
  },
  muteButtonActive: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderColor: '#ef4444',
  },
  audioErrorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(251, 191, 36, 0.15)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(251, 191, 36, 0.3)',
  },
  audioErrorText: {
    color: '#fbbf24',
    fontSize: 13,
    flex: 1,
  },
  audioGeneratingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(183, 148, 246, 0.15)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(183, 148, 246, 0.3)',
  },
  audioGeneratingText: {
    color: '#b794f6',
    fontSize: 13,
  },
  switchGuideButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2d1b4e',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
    gap: 6,
    borderWidth: 1,
    borderColor: '#7c3aed',
  },
  switchGuideText: {
    color: '#b794f6',
    fontSize: 12,
    fontWeight: '500',
  },
  switchButtonContainer: {
    alignItems: 'center',
    paddingVertical: 8,
    backgroundColor: '#1a0033',
    borderBottomWidth: 1,
    borderBottomColor: '#2d1b4e',
  },
  sectionHeading: {
    fontSize: 20,
    fontWeight: '700',
    color: '#e9d5ff',
    marginTop: 8,
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  sectionSub: {
    fontSize: 13,
    color: '#a78bd9',
    marginBottom: 12,
    fontStyle: 'italic',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: 'rgba(168,85,247,0.25)',
    marginVertical: 18,
  },
  rainbowDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ec4899',
    shadowColor: '#ec4899',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
  },
  divineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#fbbf24',
    shadowColor: '#fbbf24',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
  },
  talkBothBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#fbbf24',
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 14,
    marginTop: 12,
    shadowColor: '#fbbf24',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 6,
  },
  talkBothBtnLocked: {
    backgroundColor: 'rgba(251,191,36,0.35)',
  },
  talkBothBtnText: {
    color: '#1a0033',
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.4,
  },
  promoBadge: {
    backgroundColor: 'rgba(251,191,36,0.15)',
    borderColor: 'rgba(251,191,36,0.5)',
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    marginLeft: 6,
  },
  promoBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#fbbf24',
    letterSpacing: 1.2,
  },
  premiumBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(251,191,36,0.12)',
    borderColor: 'rgba(251,191,36,0.55)',
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    marginLeft: 6,
  },
  premiumBadgeText: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#fbbf24',
    letterSpacing: 0.9,
  },
  customNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  renameButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(251,191,36,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(251,191,36,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockOverlay: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(13,0,21,0.85)',
    borderColor: 'rgba(251,191,36,0.5)',
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  lockText: {
    fontSize: 10,
    color: '#fbbf24',
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  renameBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(8,0,15,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  renameCard: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#1a0033',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.4)',
    padding: 22,
    gap: 12,
  },
  renameTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#fbbf24',
    textAlign: 'center',
  },
  renameSub: {
    fontSize: 13,
    color: '#c4b5fd',
    textAlign: 'center',
    lineHeight: 18,
  },
  renameInput: {
    backgroundColor: 'rgba(45,27,78,0.6)',
    borderColor: 'rgba(168,85,247,0.45)',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#e9d5ff',
    fontSize: 15,
    marginTop: 4,
  },
  renameButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  renameBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  renameBtnGhost: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.4)',
  },
  renameBtnGhostText: {
    color: '#c4b5fd',
    fontWeight: '600',
  },
  renameBtnPrimary: {
    backgroundColor: '#fbbf24',
  },
  renameBtnPrimaryText: {
    color: '#1a0033',
    fontWeight: '800',
    letterSpacing: 0.3,
  },

});
