"""
Companion Guide — Premium feature.

Users with an active subscription may designate ONE spirit guide as their
"Companion." That guide:
  • Appears as a draggable floating bubble inside the app (Option B)
  • Sends 3 short "whispers" per day via scheduled LOCAL notifications
    (Option A — works without google-services.json since notifications are
    scheduled client-side; the backend supplies the text)

This module handles:
  - GET    /api/companion-guide                  current selection + freshness
  - PUT    /api/companion-guide                  pick a guide (premium-gated)
  - DELETE /api/companion-guide                  clear selection
  - GET    /api/companion-guide/whisper          one fresh whisper (cached 1h)
  - GET    /api/companion-guide/whispers/today   3 whispers for scheduling

Whispers are generated by GPT (Emergent LLM key), stay ≤ 90 chars, and are
deliberately tiny prompts so we stay cheap. Each guide's voice is preserved
via the same `GUIDE_PERSONALITIES` map already used by /spirit-guides/chat.
"""
import logging
import os
from datetime import datetime, timezone, timedelta
from typing import Optional, List

from fastapi import APIRouter, HTTPException, Request, Depends
from pydantic import BaseModel

from emergentintegrations.llm.chat import LlmChat, UserMessage

from .deps import db, EMERGENT_LLM_KEY
from .auth_utils import get_current_user
from .spirit_guides import GUIDE_PERSONALITIES, CUSTOM_GUIDE_FREE_UNTIL, _is_pride_month_now

router = APIRouter(prefix="/companion-guide", tags=["companion-guide"])

# How long a cached whisper stays "fresh" before we generate a new one.
WHISPER_CACHE_TTL_SECONDS = 60 * 60  # 1 hour

# How many whispers to return for the daily schedule
DAILY_WHISPER_COUNT = 3


class SelectCompanionBody(BaseModel):
    guide_name: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _category_for(guide_name: str) -> str:
    """Best-effort category lookup. Custom guides may be renamed by the user,
    so anything not in GUIDE_PERSONALITIES is treated as a renamed custom."""
    if guide_name in ("Ignis", "Aqua", "Terra", "Aether"):
        return "elemental"
    if guide_name in ("Solis", "Aurora", "Spectrum"):
        return "lgbtq"
    if guide_name in ("Helios", "Selene"):
        return "divine"
    if guide_name in ("Male Guide", "Female Guide"):
        return "custom"
    # Unknown name = renamed custom guide
    return "custom"


async def _user_can_use(user_doc: dict, guide_name: str) -> tuple[bool, str]:
    """Return (allowed, reason). Premium users can pick ANY guide.
    Free users can pick elemental (always), lgbtq (during June only),
    custom (until promo cutoff). Companion itself is premium-only — but we
    keep this category check here so renaming a free elemental into the
    companion slot also works gracefully."""
    is_premium = bool(user_doc.get("is_premium"))
    cat = _category_for(guide_name)
    now = datetime.now(timezone.utc)

    if cat == "elemental":
        return True, ""
    if cat == "lgbtq":
        if is_premium or _is_pride_month_now():
            return True, ""
        return False, "LGBTQ+ Guides require a subscription outside June."
    if cat == "custom":
        if is_premium or now < CUSTOM_GUIDE_FREE_UNTIL:
            return True, ""
        return False, "Custom Guides require a subscription."
    if cat == "divine":
        if is_premium:
            return True, ""
        return False, "Divine Guides require a subscription."
    return True, ""


async def _generate_whisper(guide_name: str, seeker_name: Optional[str] = None) -> str:
    """Generate a single short whisper (≤ 90 chars) from the given guide.
    Falls back to a safe default line per guide on any LLM error so the UX
    never appears broken."""
    persona = GUIDE_PERSONALITIES.get(guide_name)
    # Renamed custom guides — fall back to the generic male/female persona.
    if not persona:
        persona = GUIDE_PERSONALITIES.get("Male Guide", "")

    seeker = (seeker_name or "seeker").strip().split()[0] if seeker_name else "seeker"

    system = (
        f"{persona}\n\n"
        "You are sending a single short whisper to the seeker — a one-line "
        "message they will see as a notification on their phone. STRICT RULES:\n"
        "• MAX 90 characters total (count characters, not words).\n"
        "• ONE sentence only. No greetings, no signoffs, no emoji.\n"
        "• Speak as if leaning close to their ear: present-tense, mystical, warm.\n"
        "• Vary tone: sometimes a gentle nudge, sometimes a question, sometimes "
        "an observation, sometimes encouragement. Never two whispers alike.\n"
        "• Never use their name explicitly. Never sign off."
    )

    try:
        chat = LlmChat(
            api_key=EMERGENT_LLM_KEY,
            session_id=f"companion-whisper-{guide_name}",
            system_message=system,
        ).with_model("openai", "gpt-4o-mini")
        resp = await chat.send_message(
            UserMessage(text="Send one whisper now.")
        )
        text = (resp or "").strip().strip('"').strip("'")
        if len(text) > 110:
            text = text[:107].rstrip() + "…"
        return text or _fallback_whisper(guide_name)
    except Exception as e:
        logging.warning(f"[Companion] whisper gen failed for {guide_name}: {e}")
        return _fallback_whisper(guide_name)


def _fallback_whisper(guide_name: str) -> str:
    """Hand-written fallbacks if the LLM call fails. Keep these warm and on-brand."""
    bank = {
        "Ignis": "The fire you carry today is enough. Tend it without apology.",
        "Aqua": "Notice what your tears are trying to say. They speak first.",
        "Terra": "Plant your feet. The ground has been waiting to meet you.",
        "Aether": "The thought that keeps returning is asking to be heard.",
        "Solis": "Your light does not need permission to shine today.",
        "Aurora": "Soften your shoulders. You are allowed to be tender.",
        "Spectrum": "Whoever you are becoming, the path is already yours.",
        "Helios": "Step into the day as the sovereign of your own life.",
        "Selene": "Let the moon's silence say what your words cannot.",
        "Male Guide": "I am here. Lean on me when the day asks too much.",
        "Female Guide": "Breathe slow. You do not have to carry it all alone.",
    }
    return bank.get(guide_name, "I am near. Look for me in the small moments today.")


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@router.get("")
async def get_companion(user: dict = Depends(get_current_user)):
    """Return the user's current Companion selection (if any) along with the
    most recently cached whisper so the frontend bubble can show it
    immediately without a second round-trip."""
    user_doc = await db.users.find_one({"user_id": user["user_id"]}) or {}
    companion = user_doc.get("companion_guide") or None
    if not companion:
        return {"companion": None, "whisper": None, "whisper_at": None}

    whisper = user_doc.get("companion_whisper") or _fallback_whisper(companion)
    whisper_at = user_doc.get("companion_whisper_at")
    return {
        "companion": companion,
        "whisper": whisper,
        "whisper_at": whisper_at.isoformat() if isinstance(whisper_at, datetime) else None,
    }


@router.put("")
async def set_companion(body: SelectCompanionBody, user: dict = Depends(get_current_user)):
    """Pick a guide as your Companion. PREMIUM-ONLY (Companion bubble is a
    premium feature regardless of which guide you choose)."""
    user_doc = await db.users.find_one({"user_id": user["user_id"]}) or {}
    if not user_doc.get("is_premium"):
        raise HTTPException(
            status_code=403,
            detail="Companion Guide is a premium feature. Upgrade to keep your guide with you always.",
        )

    guide_name = (body.guide_name or "").strip()
    if not guide_name:
        raise HTTPException(status_code=400, detail="guide_name is required")

    # Verify the user can actually use this guide (handles edge cases like a
    # free-on-promo Custom Guide selection)
    allowed, reason = await _user_can_use(user_doc, guide_name)
    if not allowed:
        raise HTTPException(status_code=403, detail=reason or "Guide unavailable.")

    # Seed an initial whisper so the bubble lights up immediately on return
    name_hint = user_doc.get("display_name") or user_doc.get("name")
    whisper = await _generate_whisper(guide_name, name_hint)

    await db.users.update_one(
        {"user_id": user["user_id"]},
        {
            "$set": {
                "companion_guide": guide_name,
                "companion_whisper": whisper,
                "companion_whisper_at": datetime.now(timezone.utc),
            }
        },
    )
    return {"companion": guide_name, "whisper": whisper}


@router.delete("")
async def clear_companion(user: dict = Depends(get_current_user)):
    """Remove the Companion selection."""
    await db.users.update_one(
        {"user_id": user["user_id"]},
        {
            "$unset": {
                "companion_guide": "",
                "companion_whisper": "",
                "companion_whisper_at": "",
            }
        },
    )
    return {"success": True}


@router.get("/whisper")
async def get_whisper(user: dict = Depends(get_current_user)):
    """Return one whisper from the user's Companion. Cached for ~1h to keep
    LLM costs minimal — set `?force=1` to regenerate."""
    user_doc = await db.users.find_one({"user_id": user["user_id"]}) or {}
    companion = user_doc.get("companion_guide")
    if not companion:
        raise HTTPException(status_code=404, detail="No Companion selected")

    cached = user_doc.get("companion_whisper")
    cached_at = user_doc.get("companion_whisper_at")
    now = datetime.now(timezone.utc)

    # MongoDB returns datetimes as naive (BSON Date strips tzinfo); normalize
    # to UTC-aware before doing arithmetic with `now`.
    if isinstance(cached_at, datetime) and cached_at.tzinfo is None:
        cached_at = cached_at.replace(tzinfo=timezone.utc)

    if (
        cached
        and isinstance(cached_at, datetime)
        and (now - cached_at).total_seconds() < WHISPER_CACHE_TTL_SECONDS
    ):
        return {"whisper": cached, "cached": True, "guide": companion}

    name_hint = user_doc.get("display_name") or user_doc.get("name")
    whisper = await _generate_whisper(companion, name_hint)
    await db.users.update_one(
        {"user_id": user["user_id"]},
        {
            "$set": {
                "companion_whisper": whisper,
                "companion_whisper_at": now,
            }
        },
    )
    return {"whisper": whisper, "cached": False, "guide": companion}


@router.get("/whispers/today")
async def get_todays_whispers(user: dict = Depends(get_current_user)):
    """Return 3 whispers for today's scheduled local notifications.

    The frontend schedules these via expo-notifications' local notification
    API (no FCM/APNs needed) at three user-customizable times: morning,
    afternoon, evening."""
    user_doc = await db.users.find_one({"user_id": user["user_id"]}) or {}
    companion = user_doc.get("companion_guide")
    if not companion:
        raise HTTPException(status_code=404, detail="No Companion selected")

    name_hint = user_doc.get("display_name") or user_doc.get("name")
    # Generate the 3 whispers in parallel — cuts latency ~3x.
    import asyncio
    whispers: List[str] = await asyncio.gather(
        *[_generate_whisper(companion, name_hint) for _ in range(DAILY_WHISPER_COUNT)]
    )

    return {
        "guide": companion,
        "whispers": whispers,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
": datetime.now(timezone.utc).isoformat(),
    }
