/**
 * Oracle screen — extracted stylesheet.
 * Import as: `import { oracleStyles as styles } from '../styles/oracle.styles';`
 */
import { Dimensions, StyleSheet } from 'react-native';
import { palette } from '../theme/tokens';

const { width } = Dimensions.get('window');

export const oracleStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0d0015',
  },
  scrollContent: {
    paddingHorizontal: 12,
    paddingBottom: 20,
  },
  heroSection: {
    height: 170,
    position: 'relative',
    marginHorizontal: -12,
    marginBottom: 16,
    overflow: 'hidden',
  },
  heroImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 14,
    alignItems: 'center',
  },
  heroEyebrow: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: palette.gold,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    marginBottom: 4,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: palette.starWhite,
    textAlign: 'center',
    textShadowColor: 'rgba(168,85,247,0.7)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  heroGlyphRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6, marginBottom: 4 },
  heroGlyphLine: { width: 32, height: 1, backgroundColor: 'rgba(251,191,36,0.6)' },
  heroSubtitle: {
    fontSize: 12,
    color: palette.mist,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  backButtonText: {
    color: '#b794f6',
    fontSize: 16,
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
    marginTop: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#e9d5ff',
    marginTop: 16,
  },
  subtitle: {
    fontSize: 16,
    color: '#c4b5fd',
    marginTop: 8,
    textAlign: 'center',
  },
  spreadsContainer: {
    gap: 12,
    marginBottom: 24,
  },
  spreadCard: {
    backgroundColor: 'rgba(26, 10, 46, 0.6)',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(183, 148, 246, 0.25)',
    shadowColor: '#7c3aed',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  lockedSpreadCard: {
    opacity: 0.9,
  },
  spreadCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spreadThumbnailContainer: {
    position: 'relative',
    width: 80,
    height: 100,
  },
  spreadThumbnail: {
    width: '100%',
    height: '100%',
  },
  lockedThumbnail: {
    opacity: 0.6,
  },
  thumbnailLockOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardCountOverlay: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: 'rgba(124, 58, 237, 0.9)',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardCountOverlayText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  spreadContent: {
    flex: 1,
    padding: 12,
    paddingLeft: 14,
  },
  spreadBadges: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 4,
  },
  freeBadge: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  freeBadgeText: {
    color: '#10b981',
    fontSize: 10,
    fontWeight: 'bold',
  },
  premiumBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    gap: 3,
  },
  premiumBadgeText: {
    color: '#ffd700',
    fontSize: 10,
    fontWeight: 'bold',
  },
  spreadName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#e9d5ff',
    marginBottom: 2,
  },
  spreadDescription: {
    fontSize: 12,
    color: '#c4b5fd',
    marginBottom: 6,
  },
  lockedText: {
    color: '#8b7ba0',
  },
  spreadMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  spreadMetaText: {
    fontSize: 11,
    color: '#b794f6',
  },
  spreadArrow: {
    paddingRight: 16,
  },
  positionsPreview: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  positionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a0033',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 8,
  },
  positionNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#7c3aed',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  positionNumberText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  positionName: {
    color: '#c4b5fd',
    fontSize: 14,
    flexShrink: 0,
  },
  cardContainer: {
    alignItems: 'center',
    marginBottom: 32,
  },
  cardWrapper: {
    width: width * 0.6,
    aspectRatio: 2 / 3,
    maxWidth: 240,
  },
  cardBack: {
    flex: 1,
    backgroundColor: '#1a0033',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: '#b794f6',
    overflow: 'hidden',
  },
  cardBackPattern: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2d1b4e',
  },
  cardBackText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#e9d5ff',
    marginTop: 12,
  },
  cardBackSubtext: {
    fontSize: 14,
    color: '#c4b5fd',
    marginTop: 4,
  },
  drawButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#7c3aed',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 25,
    gap: 8,
    minWidth: 200,
    justifyContent: 'center',
  },
  drawButtonDisabled: {
    opacity: 0.6,
  },
  drawButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  historyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    gap: 8,
  },
  historyButtonText: {
    color: '#c4b5fd',
    fontSize: 16,
  },
  instructionCard: {
    backgroundColor: '#1a0033',
    borderRadius: 16,
    padding: 12,
    marginTop: 32,
    borderWidth: 1,
    borderColor: '#2d1b4e',
  },
  instructionText: {
    fontSize: 14,
    color: '#c4b5fd',
    lineHeight: 24,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
  },
  modalScrollContent: {
    padding: 12,
  },
  modalContent: {
    backgroundColor: '#1a0033',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: '#2d1b4e',
  },
  cardNavigation: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 16,
  },
  cardNavDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#2d1b4e',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardNavDotActive: {
    backgroundColor: '#7c3aed',
  },
  cardNavNumber: {
    color: '#e9d5ff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  positionLabel: {
    alignSelf: 'center',
    backgroundColor: '#7c3aed',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 16,
  },
  positionLabelText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  cardImageContainer: {
    width: '100%',
    aspectRatio: 2 / 3,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 20,
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  cardImageOverlay: {
    position: 'absolute',
    top: 16,
    right: 16,
  },
  elementBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  elementText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  cardName: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#e9d5ff',
    textAlign: 'center',
    marginBottom: 12,
  },
  cardDescription: {
    fontSize: 16,
    color: '#c4b5fd',
    textAlign: 'center',
    marginBottom: 20,
  },
  divider: {
    height: 1,
    backgroundColor: '#2d1b4e',
    marginVertical: 20,
  },
  interpretationSection: {
    marginBottom: 20,
  },
  interpretationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  interpretationTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#b794f6',
  },
  interpretation: {
    fontSize: 16,
    color: '#e9d5ff',
    lineHeight: 24,
  },
  overallReadingSection: {
    marginTop: 24,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(251,191,36,0.45)',
    backgroundColor: 'rgba(30,14,58,0.75)',
  },
  overallHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  overallTitle: {
    color: '#fbbf24',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  overallDivider: {
    height: 1,
    backgroundColor: 'rgba(251,191,36,0.35)',
    marginBottom: 12,
  },
  overallBody: {
    color: '#e9d5ff',
    fontSize: 15,
    lineHeight: 24,
    fontStyle: 'italic',
  },

  // ---- Quantum AI chat ----
  quantumSection: {
    marginTop: 16,
    marginBottom: 8,
  },
  quantumOpenBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.55)',
    backgroundColor: 'rgba(30,14,58,0.75)',
  },
  quantumOpenLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  quantumIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(168,85,247,0.28)',
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.6)',
  },
  quantumOpenTitle: {
    color: '#e9d5ff',
    fontSize: 15,
    fontWeight: '800',
  },
  quantumOpenSubtitle: {
    color: '#c4b5fd',
    fontSize: 12,
    marginTop: 2,
  },
  quantumChat: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.55)',
    backgroundColor: 'rgba(15,5,35,0.85)',
    overflow: 'hidden',
  },
  quantumChatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(30,14,58,0.9)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(168,85,247,0.35)',
  },
  quantumChatHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  quantumHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  autoPlayPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.5)',
    backgroundColor: 'rgba(30,14,58,0.65)',
  },
  autoPlayPillOn: {
    backgroundColor: '#fbbf24',
    borderColor: '#fde68a',
  },
  autoPlayPillText: {
    color: '#c4b5fd',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  autoPlayPillTextOn: {
    color: '#0f0321',
  },
  quantumChatTitle: {
    color: '#e9d5ff',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  quantumMessages: {
    maxHeight: 320,
  },
  quantumMessagesContent: {
    padding: 12,
    gap: 8,
  },
  quantumEmpty: {
    color: '#9f7aea',
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: 19,
    textAlign: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  chatBubble: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    maxWidth: '90%',
    marginBottom: 8,
  },
  chatBubbleUser: {
    backgroundColor: 'rgba(168,85,247,0.85)',
    alignSelf: 'flex-end',
    borderBottomRightRadius: 2,
  },
  chatBubbleAssistant: {
    backgroundColor: 'rgba(30,14,58,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.35)',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 2,
  },
  chatBubbleLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  chatBubbleLabel: {
    color: '#a855f7',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  chatSpeakerBtn: {
    marginLeft: 'auto',
    paddingLeft: 6,
  },
  chatBubbleTextUser: {
    color: '#0f0321',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  chatBubbleTextAssistant: {
    color: '#e9d5ff',
    fontSize: 14,
    lineHeight: 21,
  },
  quantumInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(168,85,247,0.35)',
    backgroundColor: 'rgba(15,5,35,0.85)',
  },
  quantumInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    color: '#e9d5ff',
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.35)',
    backgroundColor: 'rgba(30,14,58,0.8)',
  },
  quantumSendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fbbf24',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantumSendBtnDisabled: {
    backgroundColor: 'rgba(45,27,78,0.7)',
  },
  cardNavigationSection: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#2d1b4e',
  },
  cardArrows: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  arrowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    gap: 4,
  },
  arrowButtonDisabled: {
    opacity: 0.3,
  },
  arrowText: {
    color: '#b794f6',
    fontSize: 14,
    fontWeight: '600',
  },
  arrowTextDisabled: {
    color: '#4a3b6e',
  },
  cardCounter: {
    color: '#c4b5fd',
    fontSize: 14,
  },
  nextCardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#b794f6',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 16,
    marginTop: 16,
    gap: 10,
  },
  nextCardButtonText: {
    color: '#1a0033',
    fontSize: 18,
    fontWeight: 'bold',
  },
  readingCompleteBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 16,
    marginTop: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  readingCompleteText: {
    color: '#10b981',
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  modalButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  saveButton: {
    backgroundColor: '#7c3aed',
  },
  journalButton: {
    backgroundColor: '#10b981',
  },
  closeButton: {
    backgroundColor: '#2d1b4e',
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  historyModal: {
    flex: 1,
    backgroundColor: '#1a0033',
    marginTop: 60,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: '#2d1b4e',
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2d1b4e',
  },
  historyTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#e9d5ff',
  },
  emptyHistory: {
    alignItems: 'center',
    paddingTop: 80,
  },
  emptyText: {
    fontSize: 18,
    color: '#c4b5fd',
    marginTop: 16,
  },
  historyCard: {
    backgroundColor: '#2d1b4e',
    borderRadius: 16,
    margin: 12,
    padding: 16,
  },
  historyCardContent: {
    gap: 4,
  },
  historySpreadType: {
    fontSize: 18,
    fontWeight: '600',
    color: '#e9d5ff',
  },
  historyCardCount: {
    fontSize: 14,
    color: '#b794f6',
  },
  historyDate: {
    fontSize: 12,
    color: '#9f7aea',
    marginTop: 4,
  },
  audioControlsSection: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#2d1b4e',
  },
  audioLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#c4b5fd',
    marginBottom: 12,
  },
  audioButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  guideAudioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7c3aed',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    gap: 6,
  },
  guideAudioButtonDisabled: {
    opacity: 0.5,
  },
  guideAudioButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  stopAudioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    paddingVertical: 8,
    gap: 6,
  },
  stopAudioText: {
    color: '#ef4444',
    fontSize: 14,
    fontWeight: '600',
  },
  // Journal Prompt Modal Styles
  journalPromptOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  journalPromptModal: {
    backgroundColor: '#1a0033',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: '#2d1b4e',
  },
  journalPromptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  journalPromptTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#e9d5ff',
  },
  journalPromptSubtitle: {
    fontSize: 15,
    color: '#c4b5fd',
    marginBottom: 16,
    lineHeight: 22,
  },
  journalPromptInput: {
    backgroundColor: '#2d1b4e',
    borderRadius: 12,
    padding: 16,
    color: '#e9d5ff',
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#4a3b6e',
  },
  journalPromptButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  journalPromptButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  journalPromptCancel: {
    backgroundColor: '#2d1b4e',
    borderWidth: 1,
    borderColor: '#4a3b6e',
  },
  journalPromptCancelText: {
    color: '#c4b5fd',
    fontSize: 16,
    fontWeight: '600',
  },
  journalPromptSave: {
    backgroundColor: '#7c3aed',
  },
  journalPromptSaveText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
