import { StyleSheet } from 'react-native';

export const adminStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0a0014' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#2d1b4e' },
  backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#1a0033', justifyContent: 'center', alignItems: 'center' },
  title: { fontSize: 18, fontWeight: '600', color: '#fff' },
  tabs: { flexDirection: 'row', padding: 12, gap: 10 },
  tab: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 10, backgroundColor: '#1a0033', gap: 6 },
  tabActive: { backgroundColor: '#7c3aed' },
  tabText: { fontSize: 14, color: '#9f7aea', fontWeight: '500' },
  tabTextActive: { color: '#fff' },
  content: { flex: 1, padding: 16 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: '#fff', marginBottom: 12 },
  card: { backgroundColor: '#1a0033', borderRadius: 12, padding: 16, marginBottom: 16 },
  cardTitle: { fontSize: 15, fontWeight: '600', color: '#fff', marginBottom: 16 },
  successBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(16,185,129,0.1)', padding: 12, marginHorizontal: 16, borderRadius: 8, gap: 8 },
  successText: { flex: 1, color: '#10b981', fontSize: 14 },
  errorBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(239,68,68,0.1)', padding: 12, marginHorizontal: 16, borderRadius: 8, gap: 8 },
  errorText: { flex: 1, color: '#ef4444', fontSize: 14 },
  devToolsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(251,191,36,0.06)',
    borderColor: 'rgba(251,191,36,0.4)',
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 4,
    borderRadius: 10,
  },
  devToolsLeft: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  devToolsTitle: { color: '#fbbf24', fontSize: 13, fontWeight: '700' },
  devToolsRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  devToolsHint: { color: 'rgba(255,255,255,0.6)', fontSize: 11 },
  errorContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  errorTitle: { fontSize: 24, fontWeight: 'bold', color: '#ef4444', marginTop: 16 },
  emptyState: { alignItems: 'center', paddingVertical: 40 },
  emptyText: { fontSize: 16, color: '#9f7aea', marginTop: 12 },
  userCard: { flexDirection: 'row', backgroundColor: '#2d1b4e', padding: 14, borderRadius: 10, marginBottom: 10 },
  userInfo: { flex: 1 },
  userName: { fontSize: 15, fontWeight: '600', color: '#fff' },
  userEmail: { fontSize: 13, color: '#9f7aea', marginTop: 2 },
  userStats: { flexDirection: 'row', marginTop: 6, gap: 10 },
  statBadge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  statText: { fontSize: 11, color: '#c4b5fd' },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
  statusText: { fontSize: 11, fontWeight: '600', textTransform: 'capitalize' },
  codeTypeSelector: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  codeTypeBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, backgroundColor: '#2d1b4e', alignItems: 'center' },
  codeTypeBtnActive: { backgroundColor: '#7c3aed' },
  codeTypeBtnText: { color: '#9f7aea', fontWeight: '500' },
  codeTypeBtnTextActive: { color: '#fff' },
  input: { backgroundColor: '#2d1b4e', borderRadius: 8, padding: 12, color: '#fff', fontSize: 15, marginBottom: 12 },
  generateBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#7c3aed', padding: 14, borderRadius: 10, gap: 8 },
  generateBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  generatedCodeBox: { backgroundColor: '#2d1b4e', padding: 16, borderRadius: 10, marginTop: 16, alignItems: 'center' },
  generatedCodeLabel: { color: '#9f7aea', fontSize: 12, marginBottom: 4 },
  generatedCode: { color: '#10b981', fontSize: 22, fontWeight: 'bold', letterSpacing: 2 },
  sendEmailBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#7c3aed', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 6, marginTop: 12, gap: 6 },
  sendEmailBtnText: { color: '#fff', fontSize: 13, fontWeight: '500' },
  noEntries: { color: '#6b7280', fontStyle: 'italic', textAlign: 'center', paddingVertical: 20 },
  entryCard: { flexDirection: 'row', backgroundColor: '#2d1b4e', padding: 12, borderRadius: 8, marginBottom: 8 },
  entryCardIneligible: { opacity: 0.6 },
  entryInfo: { flex: 1 },
  entryName: { fontSize: 14, fontWeight: '500', color: '#fff' },
  entryEmail: { fontSize: 12, color: '#9f7aea', marginTop: 2 },
  entryStats: { flexDirection: 'row', marginTop: 6, gap: 10 },
  entryStat: { fontSize: 11, color: '#c4b5fd' },
  entryRight: { alignItems: 'flex-end', justifyContent: 'center' },
  eligibleBadge: { fontSize: 11, fontWeight: '600', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  eligible: { backgroundColor: 'rgba(16,185,129,0.2)', color: '#10b981' },
  ineligible: { backgroundColor: 'rgba(107,114,128,0.2)', color: '#6b7280' },
  selectWinnerBtn: { marginTop: 6, padding: 6, backgroundColor: 'rgba(255,215,0,0.2)', borderRadius: 6 },
  codeRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#2d1b4e' },
  codeText: { fontSize: 14, color: '#10b981', fontWeight: '600', fontFamily: 'monospace' },
  codeUsed: { color: '#6b7280', textDecorationLine: 'line-through' },
  codeInfo: { flexDirection: 'row', gap: 10 },
  codeType: { fontSize: 11, color: '#9f7aea', textTransform: 'capitalize' },
  codeStatus: { fontSize: 11, fontWeight: '500' },
  used: { color: '#6b7280' },
  unused: { color: '#10b981' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#1a0033', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '80%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: '#2d1b4e' },
  modalTitle: { fontSize: 18, fontWeight: '600', color: '#fff' },
  modalBody: { padding: 16 },
  detailLabel: { fontSize: 14, color: '#9f7aea', marginBottom: 8 },
  detailValue: { color: '#fff', fontWeight: '500' },
  actionButtons: { marginTop: 20, gap: 10 },
  clearBtn: { backgroundColor: 'rgba(16,185,129,0.2)', padding: 14, borderRadius: 10, alignItems: 'center' },
  clearBtnText: { color: '#10b981', fontWeight: '600' },
  reactivateBtn: { backgroundColor: '#7c3aed', padding: 14, borderRadius: 10, alignItems: 'center' },
  reactivateBtnText: { color: '#fff', fontWeight: '600' },
  cancelBtn: { backgroundColor: 'rgba(239,68,68,0.2)', padding: 14, borderRadius: 10, alignItems: 'center' },
  cancelBtnText: { color: '#ef4444', fontWeight: '600' },
  emailLabel: { fontSize: 14, color: '#9f7aea', marginBottom: 6, marginTop: 12 },
  emailCode: { fontSize: 20, fontWeight: 'bold', color: '#10b981', textAlign: 'center', marginBottom: 16 },
  emailButtons: { marginTop: 20 },
  sendWinnerBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#ffd700', padding: 14, borderRadius: 10, gap: 8 },
  sendWinnerBtnText: { color: '#1a0033', fontSize: 15, fontWeight: '600' },
  subTabs: { flexDirection: 'row', marginBottom: 16, gap: 8 },
  subTab: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: '#2d1b4e' },
  subTabActive: { backgroundColor: '#7c3aed' },
  subTabText: { fontSize: 13, color: '#9f7aea', fontWeight: '500' },
  subTabTextActive: { color: '#fff' },
  searchContainer: { flexDirection: 'row', marginBottom: 16, gap: 10 },
  searchInput: { flex: 1, backgroundColor: '#2d1b4e', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, color: '#fff', fontSize: 14 },
  searchButton: { width: 44, height: 44, borderRadius: 10, backgroundColor: '#7c3aed', justifyContent: 'center', alignItems: 'center' },
  adminUserCard: { borderWidth: 1, borderColor: 'rgba(255, 215, 0, 0.3)' },
  userNameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  adminIndicator: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255, 215, 0, 0.15)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, gap: 4 },
  adminIndicatorText: { fontSize: 10, fontWeight: '700', color: '#ffd700' },
  userDetailCard: { backgroundColor: '#2d1b4e', borderRadius: 12, padding: 16, marginBottom: 16 },
  userDetailHeader: { alignItems: 'center', marginBottom: 16 },
  adminBadgeLarge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255, 215, 0, 0.2)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, gap: 6, marginBottom: 10 },
  adminBadgeLargeText: { fontSize: 12, fontWeight: '700', color: '#ffd700' },
  userDetailName: { fontSize: 18, fontWeight: '600', color: '#fff', marginBottom: 4 },
  userDetailEmail: { fontSize: 14, color: '#9f7aea' },
  userDetailStats: { gap: 8 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#1a0033' },
  promoteBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#ffd700', padding: 14, borderRadius: 10, gap: 8 },
  promoteBtnText: { color: '#1a0033', fontSize: 15, fontWeight: '600' },
  demoteBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#ef4444', padding: 14, borderRadius: 10, gap: 8 },
  demoteBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  selfNote: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(159, 122, 234, 0.1)', padding: 14, borderRadius: 10, gap: 8 },
  selfNoteText: { flex: 1, color: '#9f7aea', fontSize: 13, fontStyle: 'italic' },
  statsGrid: { flexDirection: 'row', gap: 10, marginBottom: 8 },
  statCard: { flex: 1, backgroundColor: '#2d1b4e', borderRadius: 10, padding: 12, alignItems: 'center', position: 'relative' },
  statNumber: { fontSize: 28, fontWeight: 'bold', color: '#fff' },
  statLabel: { fontSize: 11, color: '#9f7aea', marginTop: 4 },
  statIcon: { position: 'absolute', top: 8, right: 8, width: 28, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  helpText: { fontSize: 13, color: '#c4b5fd', marginBottom: 16, lineHeight: 18 },
  processBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#10b981', padding: 14, borderRadius: 10, gap: 8 },
  processBtnDisabled: { opacity: 0.6 },
  processBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  emailInfoBox: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: 'rgba(159, 122, 234, 0.1)', padding: 12, borderRadius: 8, marginTop: 12, gap: 8 },
  emailInfoText: { flex: 1, fontSize: 12, color: '#9f7aea', lineHeight: 16 },
  testFlagBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f59e0b', padding: 14, borderRadius: 10, gap: 8 },
  testFlagBtnText: { color: '#1a0033', fontSize: 15, fontWeight: '600' },
  rulesList: { gap: 10 },
  ruleItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  ruleBadge: { width: 36, height: 36, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  ruleBadgeText: { fontSize: 14, fontWeight: 'bold' },
  ruleText: { flex: 1, fontSize: 14, color: '#e9d5ff' },
  actionItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#2d1b4e', gap: 12 },
  actionIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#2d1b4e', justifyContent: 'center', alignItems: 'center' },
  actionContent: { flex: 1 },
  actionResolution: { fontSize: 14, color: '#fff', fontWeight: '500', textTransform: 'capitalize' },
  actionMeta: { fontSize: 11, color: '#9f7aea', marginTop: 2 },
  flagCard: { backgroundColor: '#2d1b4e', borderRadius: 10, padding: 14, marginBottom: 12, borderLeftWidth: 3, borderLeftColor: '#f59e0b' },
  flagHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  flagUserInfo: { flex: 1 },
  flagUserName: { fontSize: 15, fontWeight: '600', color: '#fff' },
  flagUserEmail: { fontSize: 12, color: '#9f7aea', marginTop: 2 },
  flagMeta: { alignItems: 'flex-end' },
  flagTypeBadge: { backgroundColor: 'rgba(124, 58, 237, 0.2)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  flagTypeText: { fontSize: 10, fontWeight: '600', color: '#7c3aed', textTransform: 'uppercase' },
  flagDate: { fontSize: 10, color: '#6b7280', marginTop: 4 },
  flagContentPreview: { marginBottom: 12 },
  flagReason: { fontSize: 12, color: '#ef4444', fontWeight: '500', marginBottom: 4 },
  flagContentText: { fontSize: 13, color: '#c4b5fd', fontStyle: 'italic' },
  flagFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  flagWarningCount: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  flagWarningText: { fontSize: 12, color: '#f59e0b' },
  flagActions: { flexDirection: 'row', gap: 8 },
  flagActionBtn: { width: 36, height: 36, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  dismissBtn: { backgroundColor: 'rgba(16, 185, 129, 0.2)' },
  warnBtn: { backgroundColor: 'rgba(245, 158, 11, 0.2)' },
  cancelAccountBtn: { backgroundColor: 'rgba(239, 68, 68, 0.2)' },
  flagDetailSection: { marginBottom: 20 },
  flagDetailLabel: { fontSize: 12, fontWeight: '600', color: '#9f7aea', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 },
  flagDetailUserCard: { backgroundColor: '#2d1b4e', borderRadius: 10, padding: 14 },
  flagDetailUserName: { fontSize: 17, fontWeight: '600', color: '#fff' },
  flagDetailUserEmail: { fontSize: 13, color: '#9f7aea', marginTop: 2 },
  flagDetailUserStats: { flexDirection: 'row', gap: 10, marginTop: 10 },
  flagDetailStat: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(245, 158, 11, 0.15)', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, gap: 6 },
  flagDetailStatText: { fontSize: 12, color: '#f59e0b', fontWeight: '500' },
  flagReasonCard: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: 'rgba(239, 68, 68, 0.1)', borderRadius: 10, padding: 14, gap: 10 },
  flagReasonText: { flex: 1, fontSize: 14, color: '#ef4444', fontWeight: '500' },
  flagContentCard: { backgroundColor: '#2d1b4e', borderRadius: 10, padding: 14 },
  flagContentFullText: { fontSize: 14, color: '#e9d5ff', lineHeight: 20, fontStyle: 'italic' },
  flagMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8 },
  flagMetaLabel: { fontSize: 13, color: '#9f7aea' },
  flagMetaValue: { fontSize: 13, color: '#fff' },
  testFlagWarning: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(245, 158, 11, 0.1)', padding: 10, borderRadius: 8, gap: 8, marginTop: 10 },
  testFlagWarningText: { fontSize: 13, color: '#f59e0b' },
  flagActionButtons: { marginTop: 10 },
  flagActionTitle: { fontSize: 14, fontWeight: '600', color: '#fff', marginBottom: 14 },
  flagFullActionBtn: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 12, marginBottom: 10, gap: 14 },
  dismissFullBtn: { backgroundColor: 'rgba(16, 185, 129, 0.1)', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.3)' },
  warnFullBtn: { backgroundColor: 'rgba(245, 158, 11, 0.1)', borderWidth: 1, borderColor: 'rgba(245, 158, 11, 0.3)' },
  cancelFullBtn: { backgroundColor: 'rgba(239, 68, 68, 0.1)', borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.3)' },
  flagActionBtnContent: { flex: 1 },
  dismissFullBtnText: { fontSize: 15, fontWeight: '600', color: '#10b981' },
  warnFullBtnText: { fontSize: 15, fontWeight: '600', color: '#f59e0b' },
  cancelFullBtnText: { fontSize: 15, fontWeight: '600', color: '#ef4444' },
  flagActionBtnHint: { fontSize: 12, color: '#9f7aea', marginTop: 2 },
  sendWinnerEmailBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#10b981', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, gap: 4, marginTop: 6 },
  sendWinnerEmailBtnText: { fontSize: 11, fontWeight: '600', color: '#fff' },
  winnerInfoBox: { alignItems: 'center', backgroundColor: 'rgba(255, 215, 0, 0.1)', padding: 20, borderRadius: 12, marginBottom: 20, borderWidth: 1, borderColor: 'rgba(255, 215, 0, 0.3)' },
  winnerName: { fontSize: 18, fontWeight: '700', color: '#fff', marginTop: 12 },
  winnerEmail: { fontSize: 14, color: '#9f7aea', marginTop: 4 },
  winnerNote: { fontSize: 13, color: '#c4b5fd', textAlign: 'center', marginTop: 16, marginBottom: 20, lineHeight: 18 },
  moderationToggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12, marginBottom: 12 },
  moderationToggleInfo: { flex: 1, marginRight: 16 },
  moderationToggleLabel: { fontSize: 16, fontWeight: '600', color: '#fff', marginBottom: 4 },
  moderationToggleDescription: { fontSize: 12, color: '#9f7aea', lineHeight: 16 },
  moderationToggleBtn: { width: 60, height: 32, borderRadius: 16, justifyContent: 'center', paddingHorizontal: 4 },
  moderationToggleBtnActive: { backgroundColor: '#10b981' },
  moderationToggleBtnInactive: { backgroundColor: '#4b5563' },
  toggleSwitch: { width: '100%', height: '100%', justifyContent: 'center' },
  toggleKnob: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#fff' },
  toggleKnobActive: { alignSelf: 'flex-end' },
  toggleKnobInactive: { alignSelf: 'flex-start' },
  moderationStatusBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(16, 185, 129, 0.1)', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, gap: 8 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  timelineRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(124, 58, 237, 0.08)', borderRadius: 8, padding: 10, marginTop: 6, gap: 8 },
  timelineEmail: { fontSize: 13, color: '#e9d5ff', fontWeight: '600' },
  timelineMeta: { fontSize: 11, color: '#9f7aea', marginTop: 2 },
  ffBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#fbbf24', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6 },
  ffBtnText: { fontSize: 11, fontWeight: '700', color: '#1a0033' },
});
